/**
 * BookingWebAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type SettingValueType = 1 | 2 | 3 | 4;

export const SettingValueType = {
    Integer: 1 as SettingValueType,
    Float: 2 as SettingValueType,
    String: 3 as SettingValueType,
    Boolean: 4 as SettingValueType
};

