/**
 * BookingWebAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type SettingCategory = 1 | 2 | 3;

export const SettingCategory = {
    PasswordPolicy: 1 as SettingCategory,
    Email: 2 as SettingCategory,
    Login: 3 as SettingCategory
};

